version: 2

# List of jobs
jobs:
    # The build and test job
    build-test:
        working_directory: ~/my-app
        docker:
            - image: circleci/node:8.9.0-browsers
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Log the current branch
            - run:
                name: Show current branch
                command: echo ${CIRCLE_BRANCH}
            # Restore local dependencies from cache
            - restore_cache:
                keys:
                - v1-dependencies-{{ checksum "package.json" }}
                - v1-dependencies-
            # Install project dependencies
            - run:
                name: Install local dependencies
                command: npm install
            # Cache local dependencies if they don't exist
            - save_cache:
                key: v1-dependencies-{{ checksum "package.json" }}
                paths:
                    - node_modules
            # Build project
            - run:
                name: Building
                command: npm run build
            # Lint the source code
            - run:
                name: Linting
                command: npm run lint
            # E2E test
            - run:
                name: E2E Testing
                command: npm run e2e
            # Test the source code
            - run:
                name: Unit Testing
                command: npm run test -- --watch=false
    # The deploy job
    deploy:
        name: Deploy
            command:
              if [ $CIRCLE_BRANCH == $SOURCE_BRANCH ]; then
                git config --global thao.pttg@gmail.com $GH_EMAIL
                git config --global thaopttg $GH_NAME

                git clone $CIRCLE_REPOSITORY_URL out

                cd out
                git checkout $TARGET_BRANCH || git checkout --orphan $TARGET_BRANCH
                git rm -rf .
                cd ..

                npm run build

                cp -a build/. out/.

                mkdir -p out/.circleci && cp -a .circleci/. out/.circleci/.
                cd out

                git add -A
                git commit -m "Automated deployment to GitHub Pages: ${CIRCLE_SHA1}" --allow-empty

                git push origin $TARGET_BRANCH
              fi
workflows:
    version: 2
    # The build, test and deploy
    build-test_deploy:
        jobs:
            - build-test