version: 2

# List of jobs
jobs:
    # The build and test job
    build-test:
        working_directory: ~/my-app
        docker:
            - image: circleci/node:4.8.2
        steps:
            # Checkout the code from the branch into the working_directory
            - checkout
            # Run the `echo` command
            - run: echo "hello world"